# Generated by Django 3.2.6 on 2021-09-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FitnessPlan",
            new_name="TechBlogs",
        ),
    ]
